server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:33060/os_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
